name: Dave Kissane
url:  http://davekissane.github.io


permalink: pretty
markdown: redcarpet

mapping:
    provider: google_static
    zoom: 15
    dimensions:
        width: 500
        height: 300
