name: Stephen Fortune
url:  http://davekissane.github.io

permalink: /:year/:month/:day/:title.html

markdown: redcarpet

mapping:
    provider: google_static
    zoom: 15
    dimensions:
        width: 500
        height: 300
